/* "@(#)Generic.c Aug 25 20:00:18 2019" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#pragma comment( lib, "comctl32.lib" )
#define X2C_int32
#define X2C_index32
#ifndef X2C_H_
#include "X2C.h"
#endif
#define Generic_C_
#include "Windows.h"
#include "WinUser.h"
#include "CommCtrl.h"
#ifndef WholeStr_H_
#include "WholeStr.h"
#endif

#define Generic_AppName "Generic"

#define Generic_Title "Generic Application 2"

#define Generic_IDM_NEW 100

#define Generic_IDM_OPEN 101

#define Generic_IDM_SAVE 102

#define Generic_IDM_SAVEAS 103

#define Generic_IDM_PRINT 104

#define Generic_IDM_PRINTSETUP 105

#define Generic_IDM_EXIT 106

#define Generic_IDM_UNDO 200

#define Generic_IDM_CUT 201

#define Generic_IDM_COPY 202

#define Generic_IDM_PASTE 203

#define Generic_IDM_LINK 204

#define Generic_IDM_LINKS 205

#define Generic_IDC_MAIN_STATUS 601

#define Generic_IDC_MAIN_TOOL 602

#define Generic_IDSTR_FILTER 1000

#define Generic_LineLength 132

#define Generic_ScreenLines 32

typedef char line[132];

typedef line lines[32];

static HGDIOBJ PlainFont;

static HGDIOBJ BoldFont;

static lines Screen;

static HWND hStatus;

static long iStatusHeight;


static void FillScreen(char filler)
{
   long r;
   long c;
   for (r = 1l; r<=32l; r++) {
      for (c = 1l; c<=132l; c++) {
         Screen[X2C_CHKINX(r-1u,32u)][X2C_CHKINX(c-1u,132u)] = filler;
      } /* end for */
   } /* end for */
} /* end FillScreen() */


static void StatusMessage(long n, char text[], unsigned long text_len)
{
   X2C_ADDRESS tmp;
   X2C_PCOPY((void **)&text,text_len);
   SendMessageA(hStatus, 1025u, (unsigned)X2C_CHKL(n,0l,X2C_max_longint),
                *X2C_CAST((tmp = (char *)text,&tmp),X2C_ADDRESS,long,
                long *));
   X2C_PFREE(text);
} /* end StatusMessage() */

#define Generic_DefExt ""

#define Generic_Title0 "Select file to open"


static void OpenFile0(HWND owner)
{
   char filter[1001];
   OPENFILENAMEA of;
   char file[1001];
   char s[1101];
   memset((char *)filter,(char)0u,1001ul);
   LoadStringA(GetModuleHandleA(0), 1000u, filter, 1001l);
   file[0u] = 0;
   memset((char *) &of,(char)0u,X2C_CHKUL(sizeof(OPENFILENAMEA),0u,
                X2C_max_longcard));
   of.lStructSize = X2C_CHKUL(sizeof(OPENFILENAMEA),0u,X2C_max_longcard);
   of.hwndOwner = 0;
   of.lpstrFilter = filter;
   of.lpstrDefExt = (PSTR)Generic_DefExt;
   of.lpstrFile = file;
   of.nMaxFile = 1001ul;
   of.lpstrTitle = (PSTR)Generic_Title0;
   of.Flags = 0x4ul;
   if (GetOpenFileNameA(&of)) {
      wsprintfA(s, "File selected: %s", file);
      MessageBoxA(owner, s, (PSTR)"Open command", 0ul);
   }
} /* end OpenFile() */


static void onPaint(HWND hWnd, HDC hdc)
{
   RECT rect;
   HGDIOBJ hfOld;
   long maxDrop;
   long i;
   char text[31];
   hfOld = SelectObject(hdc, BoldFont);
   GetClientRect(hWnd, &rect);
   maxDrop = rect.bottom-iStatusHeight;
   WholeStr_IntToStr(iStatusHeight, text, 31ul);
   StatusMessage(2l, text, 31ul);
   SetTextColor(hdc, RGB(0u, 0u, 0u));
   SetBkMode(hdc, OPAQUE);
   for (i = 1l; i<=32l; i++) {
      rect.top = (-16l)+i*16l;
      rect.bottom = i*20l;
      WholeStr_IntToStr(rect.bottom, text, 31ul);
      StatusMessage(3l, text, 31ul);
      WholeStr_IntToStr(maxDrop, text, 31ul);
      StatusMessage(4l, text, 31ul);
      if (rect.bottom<maxDrop) {
         if ((i&1)) SelectObject(hdc, BoldFont);
         else SelectObject(hdc, PlainFont);
         DrawTextA(hdc, Screen[X2C_CHKINX(i-1u,32u)], 132l, &rect, 0x20ul);
      }
   } /* end for */
   SelectObject(hdc, hfOld);
} /* end onPaint() */

static long X2C_STDCALL WndProc(HWND, unsigned, unsigned, long);


static long X2C_STDCALL WndProc(HWND hWnd, unsigned message, unsigned wParam,
                 long lParam)
{
   long wmId;
   POINT pnt;
   HMENU hMenu;
   RECT rect;
   RECT rcStatus;
   HDC hdc;
   PAINTSTRUCT ps;
   HGDIOBJ hBrush;
   switch (message) {
   case 1u:
      hMenu = GetMenu(hWnd);
      EnableMenuItem(hMenu, 100u, 0u);
      EnableMenuItem(hMenu, 101u, 0u);
      return 0l;
   case 258u:
      FillScreen((char)wParam);
      hdc = GetDC(hWnd);
      onPaint(hWnd, hdc);
      ReleaseDC(hWnd, hdc);
      break;
   case 5u:
      SendMessageA(hStatus, 5u, 0u, 0l);
      GetWindowRect(hStatus, &rcStatus);
      iStatusHeight = rcStatus.bottom-rcStatus.top;
      break;
   case 273u:
      wmId = (long)LOWORD(wParam);
      switch (wmId) {
      case 106l:
         DestroyWindow(hWnd);
         break;
      case 100l:
         MessageBoxA(hWnd, "\'New\' menu item pressed",
                (PSTR)Generic_AppName, 0ul);
         break;
      case 101l:
         OpenFile0(hWnd);
         break;
      case 102l:
         break;
      case 103l:
         break;
      case 200l:
         break;
      case 201l:
         break;
      case 202l:
         break;
      case 203l:
         break;
      case 204l:
         break;
      case 205l:
         break;
      default:;
         return DefWindowProcA(hWnd, message, wParam, lParam);
      } /* end switch */
      break;
   case 516u:
      StatusMessage(1l, "POPUP MENU NEW", 15ul);
      pnt.x = (long)LOWORD((unsigned long)X2C_CHKL(lParam,0l,
                X2C_max_longint));
      pnt.y = (long)HIWORD((unsigned long)X2C_CHKL(lParam,0l,
                X2C_max_longint));
      ClientToScreen(hWnd, &pnt);
      hMenu = GetSubMenu(GetMenu(hWnd), 0l);
      if (hMenu) TrackPopupMenu(hMenu, 0u, pnt.x, pnt.y, 0l, hWnd, 0);
      else MessageBeep(0ul);
      break;
   case 15u:
      StatusMessage(1l, "PAINTING", 9ul);
      hdc = BeginPaint(hWnd, &ps);
      hBrush = CreateSolidBrush(RGB(0u, 0u, 255u));
      GetClientRect(hWnd, &rect);
      FillRect(hdc, &rect, hBrush);
      DeleteObject(hBrush);
      onPaint(hWnd, hdc);
      EndPaint(hWnd, &ps);
      break;
   case 2u:
      PostQuitMessage(0l);
      break;
   default:;
      return DefWindowProcA(hWnd, message, wParam, lParam);
   } /* end switch */
   return 0l;
} /* end WndProc() */


static char InitApplication(void)
{
   WNDCLASSEXA wc;
   InitCommonControls();
   wc.style = 0x3ul;
   wc.lpfnWndProc = WndProc;
   wc.cbClsExtra = 0l;
   wc.cbWndExtra = 0l;
   wc.hInstance = GetModuleHandleA(0);
   wc.hIcon = LoadIconA(wc.hInstance, (PSTR)Generic_AppName);
   wc.hCursor = LoadCursorA(0, (PSTR)32512u);
   wc.hbrBackground = 0;
   wc.lpszMenuName = (PSTR)Generic_AppName;
   wc.lpszClassName = (PSTR)Generic_AppName;
   wc.cbSize = X2C_CHKUL(sizeof(WNDCLASSEXA),0u,X2C_max_longcard);
   wc.hIconSm = LoadIconA(wc.hInstance, (PSTR)"SMALL");
   FillScreen('*');
   return (unsigned long)RegisterClassExA(&wc)!=0ul;
} /* end InitApplication() */


static long MulDiv0(unsigned long a, unsigned long b, unsigned long c)
{
   long Result;
   Result = (long)X2C_CHKUL((a*b)/c,0ul,2147483647ul);
   return Result;
} /* end MulDiv() */


static char InitFonts(HWND hWnd)
{
   HDC hdc;
   HGDIOBJ hf;
   long lfHeight;
   hdc = GetDC(hWnd);
   lfHeight = -MulDiv0(11ul, (unsigned long)X2C_CHKL(GetDeviceCaps(hdc, 90l),
                0l,X2C_max_longint), 72ul);
   hf = CreateFontA(lfHeight, 0l, 0l, 0l, 400l, 0, 0, 0, 0u,
                OUT_DEFAULT_PRECIS, 0u, PROOF_QUALITY, 0x2u,
                (PSTR)"CONSOLAS");
   if (hf) PlainFont = hf;
   else {
      MessageBoxA(hWnd, "Plain Font creation failed!", (PSTR)"Error",
                0x30ul);
      return 0;
   }
   hf = CreateFontA(lfHeight, 0l, 0l, 0l, 700l, 0, 0, 0, 0u,
                OUT_DEFAULT_PRECIS, 0u, PROOF_QUALITY, 0x2u,
                (PSTR)"CONSOLAS");
   if (hf) BoldFont = hf;
   else {
      MessageBoxA(hWnd, "Bold Font creation failed!", (PSTR)"Error", 0x30ul);
      return 0;
   }
   return 1;
} /* end InitFonts() */

typedef long statusBarArray[5];

static statusBarArray Generic_statwidths = {100l,200l,300l,400l,-1l};


static void MakeStatusBar(RECT * rcStatus, HWND hWnd)
{
   X2C_ADDRESS tmp;
   hStatus = CreateWindowExA(0ul, (PSTR)STATUSCLASSNAME, (PSTR)"",
                (unsigned long)0x50000100ul, 0l, 0l, 0l, 0l, hWnd,
                (HMENU)601u, GetModuleHandleA(0), 0);
   SendMessageA(hStatus, 1028u, 5u,
                *X2C_CAST((tmp = (char *)Generic_statwidths,&tmp),
                X2C_ADDRESS,long,long *));
   SendMessageA(hStatus, 5u, 0u, 0l);
   GetWindowRect(hStatus, rcStatus);
   iStatusHeight = rcStatus->bottom-rcStatus->top;
} /* end MakeStatusBar() */


static char InitMainWindow(void)
{
   HWND hWnd;
   RECT rcStatus;
   hWnd = CreateWindowA((PSTR)Generic_AppName, (PSTR)Generic_Title,
                0xCF0000ul, X2C_min_longint, 0l, X2C_min_longint, 0l, 0, 0,
                GetModuleHandleA(0), 0);
   if (hWnd==0) return 0;
   if (!InitFonts(hWnd)) return 0;
   MakeStatusBar(&rcStatus, hWnd);
   ShowWindow(hWnd, SW_SHOWDEFAULT);
   UpdateWindow(hWnd);
   return 1;
} /* end InitMainWindow() */

static MSG msg;


X2C_STACK_LIMIT(100000l)
extern int main(int argc, char **argv)
{
   X2C_BEGIN(&argc,argv,1,2000000l,4000000l);
   if (sizeof(line)!=132) X2C_ASSERT(0);
   if (sizeof(lines)!=4224) X2C_ASSERT(0);
   WholeStr_BEGIN();
   if (InitApplication() && InitMainWindow()) {
      while (GetMessageA(&msg, 0, 0u, 0u)) {
         TranslateMessage(&msg);
         DispatchMessageA(&msg);
      }
   }
   X2C_EXIT();
   return 0;
}

X2C_MAIN_DEFINITION
