/* "@(#)Turbine.c Aug 22 21:14:24 2019" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef X2C_H_
#include "X2C.h"
#endif
#define Turbine_C_
#include "Windows.h"

#define Turbine_AppName "Turbine"

#define Turbine_Title "Turbine Application"

#define Turbine_IDM_NEW 100

#define Turbine_IDM_OPEN 101

#define Turbine_IDM_SAVE 102

#define Turbine_IDM_SAVEAS 103

#define Turbine_IDM_PRINT 104

#define Turbine_IDM_PRINTSETUP 105

#define Turbine_IDM_EXIT 106

#define Turbine_IDM_UNDO 200

#define Turbine_IDM_CUT 201

#define Turbine_IDM_COPY 202

#define Turbine_IDM_PASTE 203

#define Turbine_IDM_LINK 204

#define Turbine_IDM_LINKS 205

#define Turbine_IDSTR_FILTER 1000

#define Turbine_DefExt ""

#define Turbine_Title0 "Select file to open"


static void OpenFile0(HWND owner)
{
   char filter[1001];
   OPENFILENAMEA of;
   char file[1001];
   char s[1101];
   memset((char *)filter,(char)0u,1001ul);
   LoadStringA(GetModuleHandleA(0), 1000u, filter, 1001l);
   file[0u] = 0;
   memset((char *) &of,(char)0u,X2C_CHKUL(sizeof(OPENFILENAMEA),0u,
                X2C_max_longcard));
   of.lStructSize = X2C_CHKUL(sizeof(OPENFILENAMEA),0u,X2C_max_longcard);
   of.hwndOwner = 0;
   of.lpstrFilter = filter;
   of.lpstrDefExt = (PSTR)Turbine_DefExt;
   of.lpstrFile = file;
   of.nMaxFile = 1001ul;
   of.lpstrTitle = (PSTR)Turbine_Title0;
   of.Flags = 0x4ul;
   if (GetOpenFileNameA(&of)) {
      wsprintfA(s, "File selected: %s", file);
      MessageBoxA(owner, s, (PSTR)"Open command", 0ul);
   }
} /* end OpenFile() */

static long X2C_STDCALL WndProc(HWND, unsigned, unsigned, long);


static long X2C_STDCALL WndProc(HWND hWnd, unsigned message, unsigned wParam,
                 long lParam)
{
   long wmId;
   PAINTSTRUCT ps;
   HDC hdc;
   POINT pnt;
   HMENU hMenu;
   HGDIOBJ hBrush;
   RECT rect;
   switch (message) {
   case 1u:
      hMenu = GetMenu(hWnd);
      EnableMenuItem(hMenu, 100u, 0u);
      EnableMenuItem(hMenu, 101u, 0u);
      return 0l;
   case 273u:
      wmId = (long)LOWORD(wParam);
      switch (wmId) {
      case 106l:
         DestroyWindow(hWnd);
         break;
      case 100l:
         MessageBoxA(hWnd, "\'New\' menu item pressed",
                (PSTR)Turbine_AppName, 0ul);
         break;
      case 101l:
         OpenFile0(hWnd);
         break;
      case 102l:
         break;
      case 103l:
         break;
      case 200l:
         break;
      case 201l:
         break;
      case 202l:
         break;
      case 203l:
         break;
      case 204l:
         break;
      case 205l:
         break;
      default:;
         return DefWindowProcA(hWnd, message, wParam, lParam);
      } /* end switch */
      break;
   case 516u:
      pnt.x = (long)LOWORD((unsigned long)X2C_CHKL(lParam,0l,
                X2C_max_longint));
      pnt.y = (long)HIWORD((unsigned long)X2C_CHKL(lParam,0l,
                X2C_max_longint));
      ClientToScreen(hWnd, &pnt);
      hMenu = GetSubMenu(GetMenu(hWnd), 0l);
      if (hMenu) TrackPopupMenu(hMenu, 0u, pnt.x, pnt.y, 0l, hWnd, 0);
      else MessageBeep(0ul);
      break;
   case 15u:
      hdc = BeginPaint(hWnd, &ps);
      hBrush = CreateSolidBrush(RGB(0u, 0u, 255u));
      GetClientRect(hWnd, &rect);
      FillRect(hdc, &rect, hBrush);
      DeleteObject(hBrush);
      SetTextColor(hdc, RGB(255u, 255u, 255u));
      SetBkMode(hdc, TRANSPARENT);
      DrawTextA(hdc, (PSTR)"Generic application", -1l, &rect, 0x25ul);
      EndPaint(hWnd, &ps);
      break;
   case 2u:
      PostQuitMessage(0l);
      break;
   default:;
      return DefWindowProcA(hWnd, message, wParam, lParam);
   } /* end switch */
   return 0l;
} /* end WndProc() */


static char InitApplication(void)
{
   WNDCLASSEXA wc;
   wc.style = 0x3ul;
   wc.lpfnWndProc = WndProc;
   wc.cbClsExtra = 0l;
   wc.cbWndExtra = 0l;
   wc.hInstance = GetModuleHandleA(0);
   wc.hIcon = LoadIconA(wc.hInstance, (PSTR)Turbine_AppName);
   wc.hCursor = LoadCursorA(0, (PSTR)32512u);
   wc.hbrBackground = 0;
   wc.lpszMenuName = (PSTR)Turbine_AppName;
   wc.lpszClassName = (PSTR)Turbine_AppName;
   wc.cbSize = X2C_CHKUL(sizeof(WNDCLASSEXA),0u,X2C_max_longcard);
   wc.hIconSm = LoadIconA(wc.hInstance, (PSTR)"SMALL");
   return (unsigned long)RegisterClassExA(&wc)!=0ul;
} /* end InitApplication() */


static char InitMainWindow(void)
{
   HWND hWnd;
   hWnd = CreateWindowA((PSTR)Turbine_AppName, (PSTR)Turbine_Title,
                0xCF0000ul, X2C_min_longint, 0l, X2C_min_longint, 0l, 0, 0,
                GetModuleHandleA(0), 0);
   if (hWnd==0) return 0;
   ShowWindow(hWnd, SW_SHOWDEFAULT);
   UpdateWindow(hWnd);
   return 1;
} /* end InitMainWindow() */

static MSG msg;


X2C_STACK_LIMIT(100000l)
extern int main(int argc, char **argv)
{
   X2C_BEGIN(&argc,argv,1,2000000l,4000000l);
   if (InitApplication() && InitMainWindow()) {
      while (GetMessageA(&msg, 0, 0u, 0u)) {
         TranslateMessage(&msg);
         DispatchMessageA(&msg);
      }
   }
   X2C_EXIT();
   return 0;
}

X2C_MAIN_DEFINITION
