/* Generated by XDS Oberon-2 to ANSI C v4.20 translator */

#ifndef TestMemoryUsage_H_
#define TestMemoryUsage_H_
#ifndef X2C_H_
#include "X2C.h"
#endif


extern void TestMemoryUsage_BEGIN(void);


#endif /* TestMemoryUsage_H_ */
