/* "@(#)TestMemoryUsage.c Sep  2 16:18:43 2019" */
/* Generated by XDS Oberon-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef TestMemoryUsage_H_
#include "TestMemoryUsage.h"
#endif
#define TestMemoryUsage_C_
#ifndef oberonRTS_H_
#include "oberonRTS.h"
#endif
#ifndef Out_H_
#include "Out.h"
#endif

extern struct X2C_MD_STR TestMemoryUsage_desc;
struct TestMemoryUsage_ChainDesc;
extern struct X2C_TD_STR TestMemoryUsage_ChainDesc_desc;

typedef struct TestMemoryUsage_ChainDesc * Chain;


struct TestMemoryUsage_ChainDesc {
   long data[262143];
   Chain next;
};
static X2C_PROC TestMemoryUsage_ChainDesc_proc[] = {
   0
};
static void * TestMemoryUsage_ChainDesc_offs[] = {
   X2C_OFS(struct TestMemoryUsage_ChainDesc,next),
   X2C_OFS_END
};
struct X2C_TD_STR TestMemoryUsage_ChainDesc_desc = {
   sizeof(struct TestMemoryUsage_ChainDesc), "ChainDesc",
   &TestMemoryUsage_desc, 0, 0, 0,
   { &TestMemoryUsage_ChainDesc_desc, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0 },
   TestMemoryUsage_ChainDesc_proc, TestMemoryUsage_ChainDesc_offs, 0, 0, 0,
                &TestMemoryUsage_ChainDesc_desc, 0x93678150lu
};


static void CheckMaxHeapSize(void)
{
   Chain new0 = 0;
   Chain root = 0;
   short i;
   root = 0;
   new0 = 0;
   X2C_NEW(&TestMemoryUsage_ChainDesc_desc,(char **) &root,
                sizeof(struct TestMemoryUsage_ChainDesc),0);
   X2C_CHKNIL(Chain,root)->next = 0;
   i = 1;
   Out_Int(1l, 0l);
   Out_Char(0);
   for (;;) {
      X2C_NEW(&TestMemoryUsage_ChainDesc_desc,(char **) &new0,
                sizeof(struct TestMemoryUsage_ChainDesc),0);
      X2C_CHKNIL(Chain,new0)->next = root;
      root = new0;
      X2C_INCI(&i,1,-32768,32767);
      Out_Int((long)i, 0l);
      Out_Char(0);
   }
} /* end CheckMaxHeapSize() */


static void * TestMemoryUsage_offs[] = {
   X2C_OFS_END
};
static X2C_PROC TestMemoryUsage_cmds[] = { 0 };
static X2C_CHAR * TestMemoryUsage_cnms[] = { 0 };
struct X2C_MD_STR TestMemoryUsage_desc = {
  0, 0, "TestMemoryUsage",TestMemoryUsage_offs,TestMemoryUsage_cmds,
                TestMemoryUsage_cnms,&TestMemoryUsage_ChainDesc_desc
};

X2C_STACK_LIMIT(100000l)
extern int main(int argc, char **argv)
{
   X2C_BEGIN(&argc,argv,1,2000000l,0l);
   Out_BEGIN();
   oberonRTS_BEGIN();
   X2C_MODULE(&TestMemoryUsage_desc);
   if ((long)X2C_CHKUL(sizeof(struct TestMemoryUsage_ChainDesc),0u,
                2147483647u)!=1048576l) X2C_ASSERT(20ul);
   Out_Open();
   CheckMaxHeapSize();
   X2C_EXIT();
   return 0;
}

X2C_MAIN_DEFINITION
